POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom


CIRQUE_ENABLED = yes
PMW3360_ENABLE = yes

I2C_SCANNER_ENABLE = yes
CONSOLE_ENABLE=yes

COMBO_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes


